name: open_meteo_api
description: A Dart API Client for the Open-Meteo API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
  test: ^1.21.6
  very_good_analysis: ^3.1.0
