name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.2.1
  coverage: ^1.0.3
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
  test: ^1.21.6
  very_good_analysis: ^3.1.0
